name: azure-search-openai-demo
version: 1.0.0
summary: OpenAI search app environment
description: Deploys an OpenAI search demo application
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: environmentName
    name: environmentName
    description: 'Name of the Environment'
    type: string
    required: true

  - id: location
    name: location
    description: 'Location of the resources'
    type: string
    required: true

  - id: principalId
    name: principalId
    description: 'Id of the user or app to assign application roles'
    type: string
    required: true

  - id: backendServiceName
    name: backendServiceName
    description: 'Name of app service'
    type: string

  - id: storageAccountName
    name: storageAccountName
    description: 'Name of storage account'
    type: string

  - id: searchServiceName
    name: searchServiceName
    description: 'Name of search service'
    type: string    

  - id: formRecognizerServiceName
    name: formRecognizerServiceName
    description: 'Name of form recognizer service'
    type: string       